# Generated by Django 3.1 on 2020-08-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0002_auto_20200815_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hansosum',
            name='hanso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mahjong.userinfo'),
        ),
        migrations.AlterField(
            model_name='hansosum',
            name='user_id',
            field=models.CharField(max_length=4),
        ),
    ]
