# Generated by Django 3.1 on 2020-08-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0003_auto_20200815_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hansosum',
            name='hanso_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hansosum',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mahjong.userinfo'),
        ),
    ]
