# Generated by Django 3.1 on 2021-08-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0004_auto_20210808_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameStatus',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='huro_div',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='score',
        ),
    ]
