# Generated by Django 3.1 on 2020-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0004_auto_20200815_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='score',
            new_name='score_sum',
        ),
        migrations.AddField(
            model_name='hansosum',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
