# Generated by Django 3.1 on 2021-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0005_auto_20210808_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba', models.CharField(max_length=1)),
                ('kyoku', models.IntegerField()),
                ('honba', models.IntegerField()),
                ('kyotaku', models.IntegerField()),
            ],
        ),
    ]
