# Generated by Django 3.1 on 2021-08-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0007_auto_20210808_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='score',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
